### PR TITLE
Fix pieterprovoost/wktmap#4

### LINKED ISSUE #4: Feature: remove the visualize button
Instead of having to click the visualize button, we can also just listen on the on-change events of the respective fields.

### PR DESCRIPTION
**Pull request by pietercolpaert**
Fixes #4

### CODE REVIEW

**Comment by pietercolpaert** [comment]
Probably also need to be caught for EPSG field changes as well?

**Comment by pietercolpaert** [comment]
@pieterprovoost WDYT about this one? I think it’s nice to just visualize what’s in the text field without having to click the extra button?

**Comment by pieterprovoost** [comment]
Thanks, I'm sympathetic to the feature request, but I think the current solution needs a bit of work. There are a few errors in the console, changing the CRS doesn't trigger a rerender, and not all the examples are loading correctly. I'll try to spend some time on this soonish. Combining WKT and CRS in a single state variable will probably simplify things.

**Comment by pietercolpaert** [comment]
Agreed

**Comment by pieterprovoost** [comment]
Continuing in https://github.com/pieterprovoost/wktmap/tree/auto-visualize

**Comment by pietercolpaert** [comment]
Thanks! This is pretty slick now 😍

**Pull request merged**
